//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracExplorer.VSTrac.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TracExplorer.VSTrac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Remove.
        /// </summary>
        internal static string CaptionConfirmDelete {
            get {
                return ResourceManager.GetString("CaptionConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0}?.
        /// </summary>
        internal static string ConfirmDelTracServer {
            get {
                return ResourceManager.GetString("ConfirmDelTracServer", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download_FTP_00 {
            get {
                object obj = ResourceManager.GetObject("download_FTP_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Server Connectivity....
        /// </summary>
        internal static string LabelChecking {
            get {
                return ResourceManager.GetString("LabelChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Check Failed.
        /// </summary>
        internal static string LabelCheckingFailure {
            get {
                return ResourceManager.GetString("LabelCheckingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Check Successful.
        /// </summary>
        internal static string LabelCheckingSuccess {
            get {
                return ResourceManager.GetString("LabelCheckingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Favourites.
        /// </summary>
        internal static string MenuAddToFav {
            get {
                return ResourceManager.GetString("MenuAddToFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Trac Server.
        /// </summary>
        internal static string MenuNewServer {
            get {
                return ResourceManager.GetString("MenuNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string NodeAttributes {
            get {
                return ResourceManager.GetString("NodeAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string NodeComponents {
            get {
                return ResourceManager.GetString("NodeComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones.
        /// </summary>
        internal static string NodeMilestones {
            get {
                return ResourceManager.GetString("NodeMilestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorities.
        /// </summary>
        internal static string NodePriorities {
            get {
                return ResourceManager.GetString("NodePriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolutions.
        /// </summary>
        internal static string NodeResolutions {
            get {
                return ResourceManager.GetString("NodeResolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severities.
        /// </summary>
        internal static string NodeSeverities {
            get {
                return ResourceManager.GetString("NodeSeverities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses.
        /// </summary>
        internal static string NodeStatuses {
            get {
                return ResourceManager.GetString("NodeStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string NodeTickets {
            get {
                return ResourceManager.GetString("NodeTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Types.
        /// </summary>
        internal static string NodeTicketTypes {
            get {
                return ResourceManager.GetString("NodeTicketTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        internal static string NodeVersions {
            get {
                return ResourceManager.GetString("NodeVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting....
        /// </summary>
        internal static string NodeWaiting {
            get {
                return ResourceManager.GetString("NodeWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Pages.
        /// </summary>
        internal static string NodeWikiPages {
            get {
                return ResourceManager.GetString("NodeWikiPages", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_new {
            get {
                object obj = ResourceManager.GetObject("server_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon trac {
            get {
                object obj = ResourceManager.GetObject("trac", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
